### ISSUE TITLE
网络连接不上问题

### ISSUE THREAD

**Issue by yangyanglamb** [TEN-framework/TEN-Agent#371] opened 2024-10-30 12:08 UTC
**Describe the bug**
右上角网络图标显示断网

**Expected behavior**
ui能打印断连原因吗，小白搞不懂这个怎么解决哈哈哈

**Comment by yangyanglamb** [comment] 2024-10-30 13:00
##以下是docker运行日志：

2024-10-30 19:27:10 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 19:27:10 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 19:27:10 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 19:27:10 ten_agent_playground  | 
2024-10-30 19:27:10 ten_agent_playground  |  ✓ Starting...
2024-10-30 19:27:11 ten_agent_playground  |  ✓ Ready in 75ms
2024-10-30 19:31:06 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 19:31:06 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 19:31:06 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 19:31:06 ten_agent_playground  | 
2024-10-30 19:31:06 ten_agent_playground  |  ✓ Starting...
2024-10-30 19:31:06 ten_agent_playground  |  ✓ Ready in 45ms
2024-10-30 19:35:02 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 19:35:02 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 19:35:02 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 19:35:02 ten_agent_playground  | 
2024-10-30 19:35:02 ten_agent_playground  |  ✓ Starting...
2024-10-30 19:35:02 ten_agent_playground  |  ✓ Ready in 50ms
2024-10-30 19:35:28 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 19:35:28 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 19:35:28 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 19:35:28 ten_agent_playground  | 
2024-10-30 19:35:28 ten_agent_playground  |  ✓ Starting...
2024-10-30 19:35:28 ten_agent_playground  |  ✓ Ready in 68ms
2024-10-30 19:38:49 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 19:38:49 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 19:38:49 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 19:38:49 ten_agent_playground  | 
2024-10-30 19:38:49 ten_agent_playground  |  ✓ Starting...
2024-10-30 19:38:49 ten_agent_playground  |  ✓ Ready in 103ms
2024-10-30 19:39:16 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/ping Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:16 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:16 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:16 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:16 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:16 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:16 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:16 ten_agent_playground  |   port: 8080
2024-10-30 19:39:16 ten_agent_playground  | }
2024-10-30 19:39:16 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:16 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:16 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:16 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:16 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:16 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:16 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:16 ten_agent_playground  |   port: 8080
2024-10-30 19:39:16 ten_agent_playground  | }
2024-10-30 19:39:17 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/token/generate Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:17 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:17 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:17 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:17 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:17 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:17 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:17 ten_agent_playground  |   port: 8080
2024-10-30 19:39:17 ten_agent_playground  | }
2024-10-30 19:39:17 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:17 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:17 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:17 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:17 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:17 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:17 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:17 ten_agent_playground  |   port: 8080
2024-10-30 19:39:17 ten_agent_playground  | }
2024-10-30 19:39:30 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/ping Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:30 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:30 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:30 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:30 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:30 ten_agent_playground  |   port: 8080
2024-10-30 19:39:30 ten_agent_playground  | }
2024-10-30 19:39:30 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:30 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:30 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:30 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:30 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:30 ten_agent_playground  |   port: 8080
2024-10-30 19:39:30 ten_agent_playground  | }
2024-10-30 19:39:30 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/token/generate Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:30 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:30 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:30 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:30 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:30 ten_agent_playground  |   port: 8080
2024-10-30 19:39:30 ten_agent_playground  | }
2024-10-30 19:39:30 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.5:8080
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 19:39:30 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 19:39:30 ten_agent_playground  |   errno: -111,
2024-10-30 19:39:30 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 19:39:30 ten_agent_playground  |   syscall: 'connect',
2024-10-30 19:39:30 ten_agent_playground  |   address: '172.18.0.5',
2024-10-30 19:39:30 ten_agent_playground  |   port: 8080
2024-10-30 19:39:30 ten_agent_playground  | }
2024-10-30 19:57:59 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 19:57:59 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 19:57:59 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 19:57:59 ten_agent_playground  | 
2024-10-30 19:57:59 ten_agent_playground  |  ✓ Starting...
2024-10-30 19:57:59 ten_agent_playground  |  ✓ Ready in 69ms
2024-10-30 20:02:07 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/ping Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:02:07 ten_agent_playground  |   errno: -111,
2024-10-30 20:02:07 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:02:07 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:02:07 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:02:07 ten_agent_playground  |   port: 8080
2024-10-30 20:02:07 ten_agent_playground  | }
2024-10-30 20:02:07 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:02:07 ten_agent_playground  |   errno: -111,
2024-10-30 20:02:07 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:02:07 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:02:07 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:02:07 ten_agent_playground  |   port: 8080
2024-10-30 20:02:07 ten_agent_playground  | }
2024-10-30 20:02:07 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/token/generate Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:02:07 ten_agent_playground  |   errno: -111,
2024-10-30 20:02:07 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:02:07 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:02:07 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:02:07 ten_agent_playground  |   port: 8080
2024-10-30 20:02:07 ten_agent_playground  | }
2024-10-30 20:02:07 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:02:07 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:02:07 ten_agent_playground  |   errno: -111,
2024-10-30 20:02:07 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:02:07 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:02:07 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:02:07 ten_agent_playground  |   port: 8080
2024-10-30 20:02:07 ten_agent_playground  | }
2024-10-30 20:04:23 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/ping Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:04:23 ten_agent_playground  |   errno: -111,
2024-10-30 20:04:23 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:04:23 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:04:23 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:04:23 ten_agent_playground  |   port: 8080
2024-10-30 20:04:23 ten_agent_playground  | }
2024-10-30 20:04:23 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:04:23 ten_agent_playground  |   errno: -111,
2024-10-30 20:04:23 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:04:23 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:04:23 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:04:23 ten_agent_playground  |   port: 8080
2024-10-30 20:04:23 ten_agent_playground  | }
2024-10-30 20:04:23 ten_agent_playground  | Failed to proxy http://ten_agent_dev:8080/token/generate Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:04:23 ten_agent_playground  |   errno: -111,
2024-10-30 20:04:23 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:04:23 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:04:23 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:04:23 ten_agent_playground  |   port: 8080
2024-10-30 20:04:23 ten_agent_playground  | }
2024-10-30 20:04:23 ten_agent_playground  | Error: connect ECONNREFUSED 172.18.0.4:8080
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-10-30 20:04:23 ten_agent_playground  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
2024-10-30 20:04:23 ten_agent_playground  |   errno: -111,
2024-10-30 20:04:23 ten_agent_playground  |   code: 'ECONNREFUSED',
2024-10-30 20:04:23 ten_agent_playground  |   syscall: 'connect',
2024-10-30 20:04:23 ten_agent_playground  |   address: '172.18.0.4',
2024-10-30 20:04:23 ten_agent_playground  |   port: 8080
2024-10-30 20:04:23 ten_agent_playground  | }
2024-10-30 20:28:07 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 20:28:07 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 20:28:07 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 20:28:07 ten_agent_playground  | 
2024-10-30 20:28:07 ten_agent_playground  |  ✓ Starting...
2024-10-30 20:28:07 ten_agent_playground  |  ✓ Ready in 75ms
2024-10-30 20:32:25 ten_agent_playground  |   ▲ Next.js 14.2.4
2024-10-30 20:32:25 ten_agent_playground  |   - Local:        http://localhost:3000
2024-10-30 20:32:25 ten_agent_playground  |   - Network:      http://0.0.0.0:3000
2024-10-30 20:32:25 ten_agent_playground  | 
2024-10-30 20:32:25 ten_agent_playground  |  ✓ Starting...
2024-10-30 20:32:25 ten_agent_playground  |  ✓ Ready in 47ms

**Comment by cyfyifanchen** [comment] 2024-10-31 09:20
Something wrong with your network, kill it and restart. This is duplicate of #372

**Closed by cyfyifanchen** 2024-10-31 09:20 UTC

**Comment by yangyanglamb** [comment] 2024-11-04 09:32
thank you ,I will try it again

**Comment by yangyanglamb** [comment] 2024-11-04 09:33
> 您的网络出现问题，请终止它并重新启动。这是 #372 的副本

thank you ，i will try it again
